### ISSUE TITLE
How did you managed to create the polygons

### ISSUE THREAD

**Issue by arnon001** [thewh1teagle/Magen#1]
Hi there,
I'm working on a whatsapp-bot that sending real time alarms,
I would like to know how does the code knows where is the alarm and where to put the polygons.
Please contact me if you can [here](https://discord.com/users/512965766862209025)

**Comment by thewh1teagle** [comment]
Take a look at this library which is part of the repo
https://github.com/thewh1teagle/Magen/tree/main/apps/packages/static_map
